name: TQportfolio

services:
    admin-backend:
        build:
            context: ./backend/
            dockerfile: ./src/admin/Dockerfile
        environment:
            - BUILD_TARGET=${BUILD_TARGET:-dev}
            - PORT=${ADMIN_PORT:-3000}
            - HOST=database
            - USERNAME=${ADMIN_USERNAME:-admin}
            - DB_PORT=${DATABASE_PORT:-5432}
            - DB_NAME=${DATABASE_NAME:-postgres}
            - FRONTEND_URL=${ADMIN_FRONTEND_URL:?Frontend URL required for CORS.}
            - CLOUDINARY_NAME=${CLOUDINARY_NAME:?Name required for CDN connection}
            - CLOUDINARY_PUBLIC_KEY=${CLOUDINARY_PUBLIC_KEY:?Key required for CDN connection.}
            - IMAGES_URL=${IMAGES_URL:?URL required to return images.}
        volumes:
            - data:/storage/images/
        networks:
            - admin
            - backend
        depends_on:
            database:
                condition: service_healthy
                restart: true
        develop:
            watch:
                - action: sync
                  path: ./backend/src/admin/
                  target: /app/src/admin/
                - action: sync
                  path: ./backend/src/common/
                  target: /app/src/common/
        restart: on-failure
        profiles:
            - prod
        secrets:
            - admin_password
            - cloudinary_private_key
    user-backend:
        build:
            context: ./backend/
            dockerfile: ./src/user/Dockerfile
        volumes:
            - data:/storage/images/
        networks:
            user:
            backend:
        depends_on:
            database:
                condition: service_healthy
                restart: true
        develop:
            watch:
                - action: sync
                  path: ./backend/src/user/
                  target: /app/src/
                - action: sync
                  path: ./backend/src/common/
                  target: /app/src/common/
        environment:
            - BUILD_TARGET=${BUILD_TARGET:-dev}
            - PORT=${USER_PORT:-2800}
            - USERNAME=${USER_USERNAME:-frontend}
            - HOST=database
            - DB_PORT=${DATABASE_PORT:-5432}
            - DB_NAME=${DATABASE_NAME:-postgres}
            - FRONTEND_URL=${USER_FRONTEND_URL:?Frontend URL required for CORS.}
            - CLOUDINARY_NAME=${CLOUDINARY_NAME:?Name required for CDN connection}
            - CLOUDINARY_PUBLIC_KEY=${CLOUDINARY_PUBLIC_KEY:?Key required for CDN connection.}
            - IMAGES_URL=${IMAGES_URL:?URL required to return images.}
        profiles:
            - prod
        secrets:
            - user_password
            - cloudinary_private_key
    tests:
        build:
            context: ./backend/
            dockerfile: ./tests/Dockerfile
        profiles:
            - tests
        depends_on:
            database:
                condition: service_healthy
                restart: true
        networks:
            - backend
        environment:
            - DB_NAME=${DATABASE_NAME:-postgres}
            - DB_PORT=${DATABASE_PORT:-5432}
        secrets:
            - postgres_password
    database:
        build: ./database/
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - POSTGRES_DB=${DATABASE_NAME}
            - ADMIN_USERNAME=${ADMIN_USERNAME}
            - USER_USERNAME=${USER_USERNAME}
            - PGPORT=${DATABASE_PORT}
            - PGUSER=postgres
            - LANG=es_ES.UTF-8
            - LANGUAGE=es_ES.UTF-8
            - LC_ALL=es_ES.UTF-8
        volumes:
            - data:/storage/database/
        networks:
            - backend
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        secrets:
            - admin_password
            - user_password
            - postgres_password
    nginx:
        build: "./nginx/"
        profiles: [ prod ]
        ports:
            - "0.0.0.0:8080:80"
            - "0.0.0.0:8090:20"
        volumes:
            - data:/storage/images/:ro
        depends_on:
            - admin-backend
        networks:
            - backend
        environment:
            - ADMIN_PORT=${ADMIN_PORT:-3000}
            - USER_PORT=${USER_PORT:-2800}
volumes:
    data:
networks:
    user:
    admin:
    backend:
secrets:
    user_password:
        file: ./secrets/user_password.txt
    admin_password:
        file: ./secrets/admin_password.txt
    postgres_password:
        file: ./secrets/postgres_password.txt
    cloudinary_private_key:
        file: ./secrets/cloudinary_private_key.txt
