services:
  user-frontend:
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend/user/src/
          target: /app/src/
  admin-frontend:
    build:
      args:
        - PUBLIC_apiURL=${DEV_ADMIN_BACKEND_URL:?Required to connect to the admin backend.}
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend/admin/src/
          target: /app/src/
  nginx:
    ports:
      - "5111:5111" # Admin frontend websocket for hmr
      - "5173:5173" # Admin frontend
      - "8080:8080" # Admin backend
      - "5174:5174" # User frontend (user backend at port 443 thus no port)
      - "5112:5112" # User frontend websocket for hmr
