services:
  payload:
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: node_modules
    stdin_open: true
    tty: true
  postgres:
    ports:
      # Since payload only has access to the database from within the same network running
      # "npm run payload migrate:create" isn't possible from within the host machine unless the port is exposed
      # and access throught localhost:5432 instead of postgres:5432
      - 5432:5432