services:
  payload:
    image: vector-portfolio-payload
    restart: unless-stopped
    build: .
    ports:
      - '3000:3000'
    volumes:
      - images:/app/media
    environment:
      - NEXT_PUBLIC_PAYLOAD_URL=${NEXT_PUBLIC_PAYLOAD_URL:?Website URL required}
    # command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      # - mongo
      - postgres
    secrets:
      - postgres-password
      - payload-secret

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none

  # Uncomment the following to use postgres
  postgres:
    restart: unless-stopped
    image: postgres:17.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password

volumes:
  # data:
  pgdata:
  images:

secrets:
  postgres-password:
    file: .secrets/postgres-password.txt
  payload-secret:
    file: .secrets/payload-secret.txt