services:
  payload:
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: 
          - node_modules
          - nginx
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_PAYLOAD_URL=http://${DOMAIN:?Website domain required}
  postgres:
    ports:
      # Since payload only has access to the database from within the same network running
      # "npm run payload migrate:create" isn't possible from within the host machine unless the port is exposed
      # and access throught localhost:5432 instead of postgres:5432
      - 5432:5432
    volumes: !override
      - pgdata_dev:/var/lib/postgresql/data
  nginx:
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: rebuild
          path: ./nginx/templates
          target: /etc/nginx/templates/
    ports:
      -  1001:443

volumes:
  pgdata_dev: