version: '3.8'
name: TQportfolio

services:
    admin-land-backend:
        build: ./backend/admin/
        volumes:
            - data:/storage/images/
            - data:/storage/database/
        networks:
            admin:
            backend:
        depends_on:
            - database
    # user-land-backend:
    #     build: ./backend/user/
    #     volumes:
    #         - data:/storage/database/
    #         - data:/storage/images/
    #     networks:
    #         user:
    #         backend:
    #     depends_on:
    #         - database
    database:
        build: ./database/
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=main
            - LANG=es_ES.UTF-8
            - LANGUAGE=es_ES.UTF-8
            - LC_ALL=es_ES.UTF-8
        volumes:
            - data:/storage/database/
        networks:
            backend:
    nginx:
        build: "./nginx/"
        ports:
            - "8080:80"
        volumes:
            - data:/storage/images/:ro
            - data:/storage/frontend/user/:ro
            - data:/storage/frontend/admin/:ro
        depends_on:
            - admin-land-backend
        networks:
            - backend
volumes:
    data:
networks:
    user:
    admin:
    backend:
