services:
  payload:
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: 
          - node_modules/
          - varnish/
    environment:
      - NEXT_PUBLIC_PAYLOAD_URL=http://${DOMAIN:?Website domain required}
  postgres:
    ports:
      # Since payload only has access to the database from within the same network running
      # "npm run payload migrate:create" isn't possible from within the host machine unless the port is exposed
      # and access throught localhost:5432 instead of postgres:5432
      - 5432:5432
    volumes: !override
      - pgdata_dev:/var/lib/postgresql/data
  varnish:
    ports:
      - 1001:80
    develop:
      watch:
        - path: ./varnish
          action: sync+restart
          target: /etc/varnish/

volumes:
  pgdata_dev: