name: TQportfolio

services:
    admin-land-backend:
        build:
            context: ./backend/admin/
            target: ${BUILD_TARGET}
        environment:
            - PORT=${ADMIN_PORT}
            - HOST=database
            - USERNAME=${ADMIN_USERNAME}
            - PASSWORD=${ADMIN_PASSWORD}
            - DB_PORT=${DATABASE_PORT}
            - DB_NAME=${DATABASE_NAME}
            - DB_PORT=${DATABASE_PORT}
        volumes:
            - data:/storage/images/
            - data:/storage/database/
        networks:
            - admin
            - backend
        depends_on:
            - database
        develop:
            watch:
                - action: sync
                  path: ./backend/admin/src/
                  target: /app/src/
                - action: rebuild
                  path: ./backend/admin/package.json
                  target: /app/
    # user-land-backend:
    #     build: ./backend/user/
    #     volumes:
    #         - data:/storage/database/
    #         - data:/storage/images/
    #     networks:
    #         user:
    #         backend:
    #     depends_on:
    #         - database
    database:
        build: ./database/
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
            - ADMIN_USERNAME=${ADMIN_USERNAME}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - USER_USERNAME=${USER_USERNAME}
            - USER_PASSWORD=${USER_PASSWORD}
            - PGPORT=${DATABASE_PORT}
            - LANG=es_ES.UTF-8
            - LANGUAGE=es_ES.UTF-8
            - LC_ALL=es_ES.UTF-8
        volumes:
            - data:/storage/database/
        networks:
            - backend
    nginx:
        build: "./nginx/"
        ports:
            - "8080:80"
        volumes:
            - data:/storage/images/:ro
            - data:/storage/frontend/user/:ro
            - data:/storage/frontend/admin/:ro
        depends_on:
            - admin-land-backend
        networks:
            - backend
volumes:
    data:
networks:
    user:
    admin:
    backend:
