services:
  payload:
    image: vector-portfolio-payload
    restart: unless-stopped
    build: .
    volumes:
      - images:/app/media
    environment:
      - NEXT_PUBLIC_PAYLOAD_URL=https://${DOMAIN:?Website domain required}
      - SMTP_HOST=${SMTP_HOST:?SMTP_HOST required for email functionality}
      - EMAIL_USER=${EMAIL_USER:?EMAIL_USER required for email functionality}
    depends_on:
      - postgres
      - nginx
    secrets:
      - postgres-password
      - payload-secret
      - email-password
  postgres:
    restart: unless-stopped
    image: postgres:17.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
  nginx:
    build:
      context: ./nginx
      args:
        ENABLED_MODULES: cachepurge
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    environment:
      - NGINX_HOST=${DOMAIN:?Website domain required}
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/${DOMAIN:?Website domain required}
        target: /certificates/nginx/
volumes:
  pgdata:
  images:

secrets:
  postgres-password:
    file: .secrets/postgres-password.txt
  payload-secret:
    file: .secrets/payload-secret.txt
  email-password:
    file: .secrets/email-password.txt