#!/bin/bash

set -e

# Trap errors and print the error message
trap 'echo "Error on line $LINENO: $BASH_COMMAND"' ERR

psql -U postgres << EOF
BEGIN;

CREATE USER $ADMIN_USERNAME WITH PASSWORD '$ADMIN_PASSWORD';
CREATE USER $USER_USERNAME WITH PASSWORD '$USER_PASSWORD';

GRANT CREATE ON SCHEMA public TO $ADMIN_USERNAME;
GRANT CREATE ON DATABASE postgres TO $ADMIN_USERNAME;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $ADMIN_USERNAME;
ALTER DEFAULT PRIVILEGES FOR ROLE $ADMIN_USERNAME IN SCHEMA public GRANT SELECT ON TABLES TO $USER_USERNAME;

CREATE SCHEMA IF NOT EXISTS administration AUTHORIZATION $ADMIN_USERNAME;

COMMIT;
EOF
