#!/bin/bash

set -e

# Trap errors and print the error message
trap 'echo "Error on line $LINENO: $BASH_COMMAND"' ERR

psql -U postgres << EOF
BEGIN;
CREATE USER $ADMIN_USERNAME WITH PASSWORD '$ADMIN_PASSWORD';

CREATE USER $USER_USERNAME WITH PASSWORD '$USER_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $ADMIN_USERNAME;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $USER_USERNAME;

COMMIT;
EOF
