ALTER TABLE image ADD COLUMN bg_color VARCHAR(7) NOT NULL DEFAULT '#101214';
ALTER TABLE main_page_config ADD COLUMN bg_color VARCHAR(7) NOT NULL DEFAULT '#101214';
ALTER TABLE main_page_config ADD COLUMN image_size SMALLINT NOT NULL DEFAULT 100;
ALTER TABLE sculpture_data ADD COLUMN bg_color VARCHAR(7) NOT NULL DEFAULT '#101214';
